#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs xenomorphic onto your system into ~/.local, making it available as ~/.local/bin/xed.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export XENOMORPHIC_CHANNEL=$(<crates/xenomorphic/RELEASE_CHANNEL)
export XENOMORPHIC_UPDATE_EXPLANATION="You need to fetch and rebuild xenomorphic in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="xenomorphic-linux-${arch}.tar.gz"
export XENOMORPHIC_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
