#!/usr/bin/env bash

set -euo pipefail

release_tag="${1:-$GITHUB_REF_NAME}"

for file_to_upload in ./release-artifacts/*; do
    [ -f "$file_to_upload" ] || continue
    gh release upload "$release_tag" "$file_to_upload" --clobber
done
